#!/bin/bash
grep -i bin /etc/passwd | wc -l
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[master 1a0b48d] count that word
 1 file changed, 4 insertions(+)
 mode change 100644 => 100755 0x02-shell_redirections/15-countthatword
[master b7dbcbe] count that word
 2 files changed, 4 insertions(+), 1 deletion(-)
[master e2fe9f0] count that word
 2 files changed, 3 insertions(+), 1 deletion(-)
